### PR TITLE
WRQ-7224: Fixed `Scroller` to stop propagation of 'keyup' event when back key moves focus inside a scroller

### PR DESCRIPTION
**Pull request by 0x64**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
When a user press back key on a scroll thumb of a scroller with focusableScrollbar that is rendered inside FixedPopupPanels, Scroller moves focus to the scroll body and FixedPopupPanels forwards 'onBack' event to app at the same time. So, the app changes a view to show up another panel. After all, a user feels the scroll body is flashing.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Moving focus to the scroll body is essential in a11y support to read out its contents. Also, there should be a chance to focus the scroll body if there are spottable elements inside the body. To accomplish this goal, 'onBack' event derived from keyup needs to be prevented from dispatching when Scroller catch back key input derived from keydown.
So, fixed `Scroller` to consume a keyup event too when it needs to consume keydown event.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-7224

### Comments
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek (sc.baek@lge.com)

### CODE REVIEW

**Comment by seunghoh** [comment]
Let's add the unit test to cover the updated functions. 
Don't we need to add this scenario on qa-sampler?

**Comment by 0x64** [comment]
Note for merger: to avoid an expected conflict of CHANGELOG.md, I did not update it. Before merging, please let me know so that I can commit the changelog.

**Review by juwonjeong — APPROVED** [review]
LGTM

**Review by seunghoh — APPROVED** [review]
LGTM

**Pull request merged**
