### PR TITLE
Feature/WRN-19924: Add color picker control in storybook

### PR DESCRIPTION
**Pull request by vladut-clapou-lgp**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Added storybook color picker control for changing brush, canvas and fill color for drawing component.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRN-19924

### CODE REVIEW

**Review by adrian-cocoara-lgp — APPROVED** [review]
LGTM

**Review by daniel-stoian-lgp — APPROVED** [review]

**Comment by juwonjeong** [comment]
@vladut-clapou-lgp , I have some questions about color picker controls. 

Should showDrawingControls be set to false to change brush color with Control > Draw > brushColor menu?
I cannot change brush color with color picker control in storybook. 

Also as I tested, sampler occurred ```TypeError: Cannot destructure property 'r' of 'hexToRgb(...)' as it is null``` with below arguments ```?path=/story/sandstone-drawing--drawing&args=brushColor:!rgba(147,159,73,1)```.

Could you please check this issue?

**Comment by vladut-clapou-lgp** [comment]
@juwonjeong Yes, you have to set `showDrawingControls` to false in order to change the brush, canvas or fill color from storybook control.
I will have a look at the other issue and let you know when I have something.

**Review by juwonjeong — APPROVED** [review]
Yes, It''s fixed and sampler loaded properly.
LGTM

**Pull request merged**
