### PR TITLE
WRP-11047:Picker: add `type` property to `onChange` event object

### PR DESCRIPTION
**Pull request by hoeunryuLG**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
`type: "onChange"` is missing in the object passed when `onChange` is called.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Add `type: "onChange"` in the event object.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
`type: "onChange"` must be included in the sampler output in the Actions tab when clicking next or prev buttons.

### Links
[//]: # (Related issues, references)
WRP-11047

### Comments
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>

### CODE REVIEW

**Review by juwonjeong — APPROVED** [review]
LGTM

**Comment by hoeunryuLG** [comment]
The PR has been updated
- to include a CHANGELOG entry.
- merged with the latest develop branch

**Comment by hoeunryuLG** [comment]
The PR has been updated to change the CHANGELOG entry.

**Comment by hoeunryuLG** [comment]
The PR has been updated to reorder the entry of CHANGELOG.

**Pull request merged**
