### PR TITLE
WRQ-7861: Added if options to the maxLength and minLength controls in the sampler of the input component

### PR DESCRIPTION
**Pull request by mmyelyn**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Unrelated properties should not be visible in the sampler to avoid confusing users.
Allows you to enable or disable some properties when the value of a particular property changes. 

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added if option to the maxLength and minLength controls in the sampler of the input component.
Storybook supports 'disable controls for specific properties' as a if option.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-7861

### Comments
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim (myelyn.kim@lge.com)

### CODE REVIEW

**Comment by seunghoh** [comment]
@mmyelyn Please check on documentation on checklist

**Comment by mmyelyn** [comment]
> @mmyelyn Please check on documentation on checklist

@seunghoh This is only changes for sample, so i don't think need to check on documentation on checklist.
Please let me know if I missed anything.

**Comment by juwonjeong** [comment]
> > @mmyelyn Please check on documentation on checklist
> 
> @seunghoh This is only changes for sample, so i don't think need to check on documentation on checklist. Please let me know if I missed anything.

@mmyelyn I think it should be checked, as documentation is not needed

**Review by juwonjeong — APPROVED** [review]
LGTM

**Review by seunghoh — CHANGES_REQUESTED** [review]
1. Let's hide the `length` when `customize min/max` is `true`
2. This is not related to the PR but i'd like to check. Would you please check the submit button show/hide logic?  API doc is correct? or the code is correct?

**Review by seunghoh — APPROVED** [review]
💯

**Pull request merged**
