### PR TITLE
WRN-19985: Fix ui test fail on jenkins(VirtualList, Scroller)

### PR DESCRIPTION
**Pull request by dongsuwon**
Enact-DCO-1.0-Signed-off-by: Dongsu Won (dongsu.won@lgepartner.com)

### Checklist
* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
- Need to change test way to use only 5-way mode(QWT-2317).
- Need to revert Scroller ui-test(QWT-2662) to work.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- Change test way for VirtualList ui-test(QWT-2137).
- Revert Scroller ui-test(QWT-2662) to work.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]:# (Related issues, references)
WRN-19985
QWT-2137
QWT-2662
### Comments
Test result is changed by Ux change.

### CODE REVIEW

**Comment by jeonghee27** [comment]
I think the PR description is wrong with this code change.

And Could you please add one more validation into QWT-2137?
I think below is needed.
		await expectFocusedItem(20); // or 21?

**Comment by dongsuwon** [comment]
> I think the PR description is wrong with this code change.
> 
> And Could you please add one more validation into QWT-2137? I think below is needed. await expectFocusedItem(20); // or 21?

I fixed PR description and add check focused item code. Thanks for review!

**Comment by jeonghee27** [comment]
link https://github.com/enactjs/sandstone/pull/1217

**Review by jeonghee27 — APPROVED** [review]
LGTM

**Pull request merged**
